# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2705e11d566d5071dbe071e4c0f22676c676609287e96b161ed5b65aeacaaade84e65edd645938458492e3acee288321fc8e2b34f6c04cb44f0b83fec93c8b77

test:
  secret_key_base: 396669cc38d966b53d600fa8b78ad3f6cd5670fd372eeb0b4ec0281ba1e7ca9da88953e84e290e92775e7a86d34f743a4da4350f2227406ddd0db65f90937d5b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
